CREATE DATABASE HEALTHCARE;
USE HEALTHCARE;
SELECT * FROM HEALTHCARE_PROJECT;
-- A. Patient Demographics --
SELECT GENDER,COUNT(*) AS PATIENT_COUNT FROM HEALTHCARE_PROJECT GROUP BY GENDER;
-- B. Monthly Admission Trend --
SELECT ADM_MONTH AS MONTH ,COUNT(*) AS PATIENTS_COUNT FROM HEALTHCARE_PROJECT GROUP BY MONTH ORDER BY MONTH;
-- C. Most common medical conditions --
SELECT MEDICAL_CONDITION ,COUNT(*) AS TOTAL_PATIENTS FROM HEALTHCARE_PROJECT GROUP BY MEDICAL_CONDITION;
-- D. Avg. billing amount by admission type --
SELECT ADMISSION_TYPE,AVG(BILLING_AMOUNT) AS AVG_BILLING_AMT FROM HEALTHCARE_PROJECT GROUP BY ADMISSION_TYPE;
-- E.  Length of stay by condition --
SELECT MEDICAL_CONDITION,AVG(LOF_IN_DAYS) AVG_STAY_DAYS FROM HEALTHCARE_PROJECT GROUP BY MEDICAL_CONDITION;
-- F. Test results vs medication
SELECT TEST_RESULTS,MEDICATION,COUNT(*) TOTAL_PATIENTS FROM HEALTHCARE_PROJECT GROUP BY TEST_RESULTS,MEDICATION ORDER BY TEST_RESULTS, TOTAL_PATIENTS DESC;
-- G. TOP 10 hospitals highest average billing amount --
SELECT HOSPITAL,AVG(BILLING_AMOUNT) AS AVG_BILL_AMT FROM HEALTHCARE_PROJECT GROUP BY HOSPITAL ORDER BY AVG_BILL_AMT DESC LIMIT 10;
-- H. Which medical conditions are most common among older patients (e.g., 60+ years) --
SELECT MEDICAL_CONDITION ,COUNT(*) AS PATIENTS FROM HEALTHCARE_PROJECT WHERE AGE>=60 GROUP BY MEDICAL_CONDITION ORDER BY PATIENTS DESC;
